### ISSUE TITLE
Website demo not working on Chrome Windows 7

### ISSUE THREAD

**Issue by maxpaynestory** [JaredCubilla/goodnight#7]
http://jaredcubilla.github.io/goodnight/demo/

not working on Chrome, Windows 7

**Comment by JaredCubilla** [comment]
Could you specify? Right now the demo is kinda terrible, it just changes the background-color, so that may cause confusion.

**Comment by maxpaynestory** [comment]
Chrome shows a blank page with background color rgb(236, 240, 241).

**Comment by JaredCubilla** [comment]
Sorry about that. I've gotten lazy, and I didn't bother actually doing a full on demo. This was supposed to happen.

Someone just sent a pull request for a demo, so I think it should show up soon.

**Comment by maxpaynestory** [comment]
Sure will let you know if it gets fixed.
